version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "9000:5173"
    depends_on:
      - backend

  backend:
    build: ./api
    ports:
      - "3030:3030"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.36
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./api/src/database/tables.sql:/docker-entrypoint-initdb.d/tables.sql

volumes:
  mysql-data: