version: '3.8'

services:

  api:
    build: ./
    ports:
      - "3333:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.36
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3300:3306"