version: '3.8'

services:

  api:
    build: ./
    ports:
      - "3000:3030"
    depends_on:
      - mysql
    
  mysql:
    image: mysql:8.0.36
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./src/database/tables.sql:/docker-entrypoint-initdb.d/tables.sql
    ports:
      - "3306:3306"